[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = ["pip install --user -r requirements.txt"]

[start]
cmd = "python -m chainlit run app.py --host 0.0.0.0 --port $PORT --headless"
